"""Contracts shared by AFL JSON collectors."""

from .contracts import (
    CFS_ERROR_AUTH,
    CFS_ERROR_NOT_PUBLISHED,
    ENDPOINTS,
    IDENTIFIER_TYPES,
    RETRYABLE_HTTP_STATUSES,
    SOURCE_PRIORITY,
    SUCCESS_HTTP_STATUSES,
    EndpointDefinition,
    get_endpoint,
)
from .client import (
    AflJsonAuthenticationError,
    AflJsonClient,
    AflJsonError,
    AflJsonHttpError,
    AflJsonInvalidResponse,
    AflJsonResourceUnavailable,
    AflJsonResponse,
    AflJsonTransportError,
    HttpPolicy,
    WMCTokenProvider,
)
from .collectors import (
    CollectionError,
    CollectionDiagnostic,
    CollectionResult,
    PaginationError,
    PublicAflCollector,
    PlayerCollectionResult,
    RawResponseWriter,
    resolve_competition,
    select_season,
)

__all__ = [
    "CFS_ERROR_AUTH",
    "CFS_ERROR_NOT_PUBLISHED",
    "ENDPOINTS",
    "IDENTIFIER_TYPES",
    "RETRYABLE_HTTP_STATUSES",
    "SOURCE_PRIORITY",
    "SUCCESS_HTTP_STATUSES",
    "EndpointDefinition",
    "get_endpoint",
    "AflJsonAuthenticationError",
    "AflJsonClient",
    "AflJsonError",
    "AflJsonHttpError",
    "AflJsonInvalidResponse",
    "AflJsonResourceUnavailable",
    "AflJsonResponse",
    "AflJsonTransportError",
    "HttpPolicy",
    "WMCTokenProvider",
    "CollectionError",
    "CollectionDiagnostic",
    "CollectionResult",
    "PaginationError",
    "PublicAflCollector",
    "PlayerCollectionResult",
    "RawResponseWriter",
    "resolve_competition",
    "select_season",
]
