"""Contracts shared by AFL JSON collectors."""

from .contracts import (
    CFS_ERROR_AUTH,
    CFS_ERROR_NOT_PUBLISHED,
    ENDPOINTS,
    IDENTIFIER_TYPES,
    RETRYABLE_HTTP_STATUSES,
    SOURCE_PRIORITY,
    SUCCESS_HTTP_STATUSES,
    EndpointDefinition,
    get_endpoint,
)
from .client import (
    AflJsonAuthenticationError,
    AflJsonClient,
    AflJsonError,
    AflJsonHttpError,
    AflJsonInvalidResponse,
    AflJsonResourceUnavailable,
    AflJsonResponse,
    AflJsonTransportError,
    HttpPolicy,
    WMCTokenProvider,
)
from .collectors import (
    CollectionError,
    CollectionDiagnostic,
    CollectionResult,
    PaginationError,
    PublicAflCollector,
    PlayerCollectionResult,
    RawResponseWriter,
    is_current_season,
    resolve_competition,
    resolve_current_season,
    select_season,
)
from .rosters import (
    CONTEXT_TYPES,
    ROSTER_COLLECTOR_VERSION,
    MatchRosterCollector,
    RosterChanges,
    RosterCollectionResult,
    RosterPersistenceSummary,
    RosterStatus,
    compare_rosters,
    current_roster_context,
    current_roster_selections,
    current_roster_teams,
    persist_match_rosters,
    resolve_canonical_match as resolve_canonical_roster_match,
    resolve_canonical_player as resolve_canonical_roster_player,
    resolve_canonical_team as resolve_canonical_roster_team,
)
from .player_stats import (
    CANONICAL_STAT_FIELDS,
    CanonicalPlayerStat,
    MatchPlayerStatsCollector,
    PlayerStatDiagnostic,
    PlayerStatsCollectionResult,
    PlayerStatsStatus,
    normalise_player_stats,
    resolve_canonical_match_status,
    upsert_player_stats,
)
from .match_status import (
    MatchLifecycle, MatchStatusDiagnostic, MatchStatusResolution,
    later_match_status, normalise_match_status, persist_match_status_resolution,
    reconcile_match_status,
)
from .match_period import (
    MatchPeriodState, derive_match_period_state, extract_match_clock_periods,
    match_period_state_from_payload,
)
from .bootstrap import BootstrapSummary, persist_afl_metadata
from .player_persistence import (
    PlayerIdentityConflict, PlayerPersistenceSummary, persist_player_seasons,
)
from .orchestration import (
    ALL_FAMILIES, SUPPORTED_FAMILIES, UNSUPPORTED_FAMILIES,
    BatchCollectionError, CollectionOrchestrator, CollectionRequest,
)

__all__ = [
    "CFS_ERROR_AUTH",
    "CFS_ERROR_NOT_PUBLISHED",
    "ENDPOINTS",
    "IDENTIFIER_TYPES",
    "RETRYABLE_HTTP_STATUSES",
    "SOURCE_PRIORITY",
    "SUCCESS_HTTP_STATUSES",
    "EndpointDefinition",
    "get_endpoint",
    "AflJsonAuthenticationError",
    "AflJsonClient",
    "AflJsonError",
    "AflJsonHttpError",
    "AflJsonInvalidResponse",
    "AflJsonResourceUnavailable",
    "AflJsonResponse",
    "AflJsonTransportError",
    "HttpPolicy",
    "WMCTokenProvider",
    "CollectionError",
    "CollectionDiagnostic",
    "CollectionResult",
    "PaginationError",
    "PublicAflCollector",
    "PlayerCollectionResult",
    "RawResponseWriter",
    "is_current_season",
    "resolve_competition",
    "resolve_current_season",
    "select_season",
    "CONTEXT_TYPES",
    "ROSTER_COLLECTOR_VERSION",
    "MatchRosterCollector",
    "RosterChanges",
    "RosterCollectionResult",
    "RosterPersistenceSummary",
    "RosterStatus",
    "compare_rosters",
    "current_roster_context",
    "current_roster_selections",
    "current_roster_teams",
    "persist_match_rosters",
    "resolve_canonical_roster_match",
    "resolve_canonical_roster_player",
    "resolve_canonical_roster_team",
    "CANONICAL_STAT_FIELDS",
    "CanonicalPlayerStat",
    "MatchPlayerStatsCollector",
    "PlayerStatDiagnostic",
    "PlayerStatsCollectionResult",
    "PlayerStatsStatus",
    "normalise_player_stats",
    "resolve_canonical_match_status",
    "upsert_player_stats",
    "MatchLifecycle",
    "MatchStatusDiagnostic",
    "MatchStatusResolution",
    "later_match_status",
    "normalise_match_status",
    "persist_match_status_resolution",
    "reconcile_match_status",
    "MatchPeriodState",
    "derive_match_period_state",
    "extract_match_clock_periods",
    "match_period_state_from_payload",
    "BootstrapSummary",
    "persist_afl_metadata",
    "PlayerIdentityConflict",
    "PlayerPersistenceSummary",
    "persist_player_seasons",
    "SeasonBootstrapResult",
    "SeasonSyncOptions",
    "SeasonSyncResult",
    "SeasonSynchronizer",
    "bootstrap_afl_season",
    "ALL_FAMILIES",
    "SUPPORTED_FAMILIES",
    "UNSUPPORTED_FAMILIES",
    "BatchCollectionError",
    "CollectionOrchestrator",
    "CollectionRequest",
]

from .season_sync import (SeasonBootstrapResult, SeasonSynchronizer,
                          SeasonSyncOptions, SeasonSyncResult,
                          bootstrap_afl_season)
